# Generated by Django 3.2.21 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=20)),
                ('news', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=450)),
                ('date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
