# Generated by Django 3.2.21 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities', models.CharField(max_length=45)),
                ('details', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
    ]
