# Generated by Django 3.2.21 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('review', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
