# Generated by Django 3.2.21 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('locationl', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('id_proof', models.CharField(db_column='ID_proof', max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
